# Generated by Django 2.2.7 on 2019-11-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_content',
            field=models.TextField(default=''),
        ),
    ]
