# Generated by Django 2.2.7 on 2019-11-30 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorials', '0003_tutorial_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='date_created',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_content',
            field=models.TextField(),
        ),
    ]
